/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIdRouteImport } from './routes/trade.$id'
import { Route as SettingsShortcutsRouteImport } from './routes/settings.shortcuts'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as ApiPublicHooksBotsTickRouteImport } from './routes/api/public/hooks/bots-tick'
import { Route as ApiMarketCandlesRouteImport } from './routes/api/market/candles'
import { Route as ApiMarketQuotesRouteImport } from './routes/api/market/quotes'
import { Route as ApiNewsFeedRouteImport } from './routes/api/news/feed'
import { Route as ApiWebhooksTradingviewRouteImport } from './routes/api/webhooks/tradingview'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIdRoute = TradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBotsTickRoute = ApiPublicHooksBotsTickRouteImport.update({
  id: '/api/public/hooks/bots-tick',
  path: '/api/public/hooks/bots-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCandlesRoute = ApiMarketCandlesRouteImport.update({
  id: '/api/market/candles',
  path: '/api/market/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketQuotesRoute = ApiMarketQuotesRouteImport.update({
  id: '/api/market/quotes',
  path: '/api/market/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsFeedRoute = ApiNewsFeedRouteImport.update({
  id: '/api/news/feed',
  path: '/api/news/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTradingviewRoute = ApiWebhooksTradingviewRouteImport.update({
  id: '/api/webhooks/tradingview',
  path: '/api/webhooks/tradingview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/public/hooks/bots-tick': typeof ApiPublicHooksBotsTickRoute
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/webhooks/tradingview': typeof ApiWebhooksTradingviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/public/hooks/bots-tick': typeof ApiPublicHooksBotsTickRoute
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/webhooks/tradingview': typeof ApiWebhooksTradingviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/trade/$id': typeof TradeIdRoute
  '/api/public/hooks/bots-tick': typeof ApiPublicHooksBotsTickRoute
  '/api/market/candles': typeof ApiMarketCandlesRoute
  '/api/market/quotes': typeof ApiMarketQuotesRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/webhooks/tradingview': typeof ApiWebhooksTradingviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pro'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/trade/$id'
    | '/api/public/hooks/bots-tick'
    | '/api/market/candles'
    | '/api/market/quotes'
    | '/api/news/feed'
    | '/api/webhooks/tradingview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pro'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/trade/$id'
    | '/api/public/hooks/bots-tick'
    | '/api/market/candles'
    | '/api/market/quotes'
    | '/api/news/feed'
    | '/api/webhooks/tradingview'
  id:
    | '__root__'
    | '/'
    | '/pro'
    | '/settings/notifications'
    | '/settings/shortcuts'
    | '/trade/$id'
    | '/api/public/hooks/bots-tick'
    | '/api/market/candles'
    | '/api/market/quotes'
    | '/api/news/feed'
    | '/api/webhooks/tradingview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  TradeIdRoute: typeof TradeIdRoute
  ApiPublicHooksBotsTickRoute: typeof ApiPublicHooksBotsTickRoute
  ApiMarketCandlesRoute: typeof ApiMarketCandlesRoute
  ApiMarketQuotesRoute: typeof ApiMarketQuotesRoute
  ApiNewsFeedRoute: typeof ApiNewsFeedRoute
  ApiWebhooksTradingviewRoute: typeof ApiWebhooksTradingviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$id': {
      id: '/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bots-tick': {
      id: '/api/public/hooks/bots-tick'
      path: '/api/public/hooks/bots-tick'
      fullPath: '/api/public/hooks/bots-tick'
      preLoaderRoute: typeof ApiPublicHooksBotsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/candles': {
      id: '/api/market/candles'
      path: '/api/market/candles'
      fullPath: '/api/market/candles'
      preLoaderRoute: typeof ApiMarketCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/quotes': {
      id: '/api/market/quotes'
      path: '/api/market/quotes'
      fullPath: '/api/market/quotes'
      preLoaderRoute: typeof ApiMarketQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/feed': {
      id: '/api/news/feed'
      path: '/api/news/feed'
      fullPath: '/api/news/feed'
      preLoaderRoute: typeof ApiNewsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/tradingview': {
      id: '/api/webhooks/tradingview'
      path: '/api/webhooks/tradingview'
      fullPath: '/api/webhooks/tradingview'
      preLoaderRoute: typeof ApiWebhooksTradingviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  TradeIdRoute: TradeIdRoute,
  ApiPublicHooksBotsTickRoute: ApiPublicHooksBotsTickRoute,
  ApiMarketCandlesRoute: ApiMarketCandlesRoute,
  ApiMarketQuotesRoute: ApiMarketQuotesRoute,
  ApiNewsFeedRoute: ApiNewsFeedRoute,
  ApiWebhooksTradingviewRoute: ApiWebhooksTradingviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
